[tool.ruff]
# Включаем линтер Ruff
line-length = 120  # Максимальная длина строки (по умолчанию как в Black)

[tool.ruff.lint]
select = [
    "E",    # pycodestyle (основные ошибки стиля: отступы, пробелы, переносы строк)
    "F",    # Pyflakes (ошибки кода: неиспользуемые переменные, импорты и т.д.)
    "W",    # pycodestyle Warnings (предупреждения, например пробел перед двоеточием)
    "N",    # pep8-naming (правильные имена функций, классов, переменных)
    "B",    # flake8-bugbear (опасные места, потенциальные баги)
    "I",    # isort (правильная сортировка импортов)
    "RUF",  # собственные правила Ruff (улучшения и ловля опечаток)
]

ignore = [
    "E501",     # Игнорируем "строка длиннее 88 символов" (потому что Black сам форматирует)
    "N818",     # Игнорируем требование "Exception" в конце имени класса исключения
]

fixable = ["ALL"]   # Разрешаем Ruff автоматически исправлять все возможные ошибки
unfixable = []      # Здесь можно указать ошибки, которые НЕ нужно чинить автофиксом

# Примеры дополнительных правил, которые часто включают
extend-select = [
    "C90",  # mccabe: проверка сложности функций (предотвращает слишком сложный код)
    "UP",   # pyupgrade: советует более современный Python синтаксис
]

[tool.ruff.format]
quote-style = "double"              # Использовать двойные кавычки
indent-style = "space"              # Отступы пробелами, не табами
skip-magic-trailing-comma = false   # Следовать правилам Black для запятой в конце
line-ending = "auto"                # Конец строки под твою ОС (LF/CRLF)